MAIL_ADDRESS = "marv42+stadtbibliothek@gmail.com"
CARD_NUMBER = '90270550'
PASSWORD = 'Op4cgoztosso00000000%22%28%29'
COOKIES = {'ASPSESSIONIDAASQCADQ': "CABOLLLBCCOECAFIDDBCHLJN",
           'ASPSESSIONIDACQRCBDR': "INBMPPCDNLEJAHMLOOFLKNHJ",
           'ASPSESSIONIDACRTAADQ': "GILFJMFANOMKBFEHEONOGJEI",
           'ASPSESSIONIDCARQCACQ': "CNALLHPAGJHDOGKMMFABDAMI",
           'konto': "1",
           'weblogon259764434': "true"}
